const products = [
	{
		id: 0,
		name: "men's t-shirt",
		price: '19.99',
		image: "src/img/products/men's-t-shirt.png",
	},
	{
		id: 1,
		name: "men's shirt",
		price: '49.99',
		image: "src/img/products/men's-shirt.png",
	},
	{
		id: 2,
		name: "men's bracelet",
		price: '99.99',
		image: "src/img/products/men's-bracelet.png",
	},
	{
		id: 3,
		name: "men's jacket",
		price: '149.99',
		image: "src/img/products/men's-jacket.png",
	},
	{
		id: 4,
		name: "men's jeans",
		price: '84.99',
		image: "src/img/products/men's-jeans.png",
	},
	{
		id: 5,
		name: "men's necklace",
		price: '199.99',
		image: "src/img/products/men's-necklace.png",
	},
	{
		id: 6,
		name: "men's ring",
		price: '499.99',
		image: "src/img/products/men's-ring.png",
	},
	{
		id: 7,
		name: "men's shoes",
		price: '189.99',
		image: "src/img/products/men's-shoes.png",
	},
	{
		id: 8,
		name: "men's watch",
		price: '899.99',
		image: "src/img/products/men's-watch.png",
	},
	{
		id: 9,
		name: "women's bracelet",
		price: '129.99',
		image: "src/img/products/women's-bracelet.png",
	},
	{
		id: 10,
		name: "women's t-shirt",
		price: '59.99',
		image: "src/img/products/women's-t-shirt.png",
	},
	{
		id: 11,
		name: "women's jacket",
		price: '349.99',
		image: "src/img/products/women's-jacket.png",
	},
	{
		id: 12,
		name: "women's long sleeve",
		price: '129.99',
		image: "src/img/products/women's-long-sleeve.png",
	},
	{
		id: 13,
		name: "women's necklace",
		price: '699.99',
		image: "src/img/products/women's-necklace.png",
	},
	{
		id: 14,
		name: "women's ring",
		price: '139.99',
		image: "src/img/products/women's-ring.png",
	},
	{
		id: 15,
		name: "women's shoes",
		price: '99.99',
		image: "src/img/products/women's-shoes.png",
	},
]
